# Generated by Django 4.0 on 2022-01-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirm',
            field=models.BooleanField(null=True),
        ),
    ]
