# Generated by Django 4.0 on 2022-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='assign_store_size',
            field=models.IntegerField(default=20000),
        ),
    ]
