# Generated by Django 4.0 on 2022-02-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_assign_store_size'),
        ('cloud', '0002_filefolder_storefile_folder_id_delete_sharestorefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefolder',
            name='share_id',
        ),
        migrations.RemoveField(
            model_name='storefile',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='storefile',
            name='belong_folder_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='belong_folder_id', to='cloud.filefolder'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='upper_folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_id', to='cloud.filefolder'),
        ),
        migrations.CreateModel(
            name='ShareFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onner_id', to='account.account')),
                ('share_folder_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='share_folder_id', to='cloud.filefolder')),
                ('share_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_id', to='account.account')),
            ],
        ),
    ]
