# Generated by Django 4.0 on 2022-02-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_alter_sharefolder_share_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='share_able',
            field=models.BooleanField(default=False),
        ),
    ]
