# Generated by Django 4.0 on 2022-03-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_filefolder_share_able'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='upper_folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_id', to='cloud.filefolder'),
        ),
    ]
