# Generated by Django 4.0 on 2022-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_sharefolder_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
