# Generated by Django 4.0 on 2022-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_alter_filefolder_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefolder',
            name='share_able',
        ),
        migrations.AddField(
            model_name='filefolder',
            name='folder_path',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sharefolder',
            name='gropunum',
            field=models.IntegerField(default=0),
        ),
    ]
