# Generated by Django 4.0 on 2022-03-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_alter_filefolder_folder_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharefolder',
            old_name='gropunum',
            new_name='groupnum',
        ),
    ]
